import type { Metadata } from "next";
import "./globals.css";
import MyProfile from "@/components/myProfile";
import Navbar from "@/components/navbar";
export const metadata: Metadata = {
  title: "my resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <div className="bg-[url('/images/bg.webp')] bg-cover bg-center bg-no-repeat min-h-screen">
       <div className="grid grid-cols-12 gap-4"> 
          <div className="col-span-12 md:col-span-5 lg:col-span-4">
            <MyProfile />
          </div>

          <div className="col-span-12 md:col-span-7 lg:col-span-8">
            <Navbar />

            <div className="mt-4 text-gray-700">
              {children}
            </div>

          </div>
        </div>
       </div>
      </body>
    </html>
  );
}
